---
# General
region: "eu-west-2"

development_group: "ibe"

component: "aws-example-product-base-account"
deployment_identifier: "%{deployment_group}-%{deployment_type}-%{deployment_label}"

storage_bucket_name: "%{hiera('development_group')}-%{hiera('component')}-%{hiera('deployment_identifier')}"
storage_bucket_encryption: "AES256"

minimum_password_length: 32

admin_public_gpg_key_path: "%{cwd}/config/secrets/gpg/admin.gpg.public"

ibe_root_account_id: "635746531358"
ibe_parent_account_id: "427607157647"
ibe_management_account_id: "997812904408"
ibe_development_molybdenum_account_id: "770285404576"
ibe_production_holmium_account_id: "306130939196"
