---
development_provisioning_role_arn: "arn:aws:iam::%{hiera('ibe_development_molybdenum_account_id')}:role/cross-account-admin-role"
development_deployment_group: "ibe"
development_deployment_type: "development"
development_deployment_label: "molybdenum"

production_provisioning_role_arn: "arn:aws:iam::%{hiera('ibe_production_holmium_account_id')}:role/cross-account-admin-role"
production_deployment_group: "ibe"
production_deployment_type: "production"
production_deployment_label: "holmium"
